classdef EQ < audioPlugin
    properties
        HI_CENTER_FREQ = 8000;
        HI_GAIN = 0;

        LOW_CENTER_FREQ = 525;
        LOW_GAIN = 0;

        BAND_CENTER_FREQ = 3500;
        BAND_GAIN = 0;

        Q_factor = 0.5;

        fs = 44100;
        fn = 22050;

        THRESHOLD = -20;
        RATIO = 7;
        ATTACK = 25;
        RELEASE = 500;

        DECAY = 0.1;
        MIX = 15;

        BYPASS = 'engage';
    end

    properties (Constant)
        PluginInterface = audioPluginInterface(...
            'PluginName', 'Dale',...
            'VendorName', 'Nicolas Adler',...
            'VendorVersion','1.0.0',...
            'UniqueId', 'Nic9',...
            audioPluginGridLayout(...
            'RowHeight', [100 25 100 25 100 25 100 25],...
            'ColumnWidth', [100 100 100 100]),...
            audioPluginParameter('THRESHOLD',...
            'DisplayName', 'Threshold',...
            'Label', 'dB',...
            'Style', 'rotaryknob',...
            'Mapping', {'lin', -40, 0},...
            'Layout', [1,1],...
            'DisplayNameLocation', 'below',...
            'Filmstrip', 'Prophetic_Silver_80x80.png',...            '
            'FilmstripFrameSize', [80 80]),...
            audioPluginParameter('RATIO',...
            'DisplayName', 'Ratio',...
            'Style', 'rotaryknob',...
            'Label', ':1',...
            'Mapping', {'int', 1, 13},...
            'Layout', [1,2],...
            'DisplayNameLocation', 'below',...
            'Filmstrip', 'Prophetic_Silver_80x80.png',...
            'FilmstripFrameSize', [80 80]),...
            audioPluginParameter('ATTACK',...
            'DisplayName', 'Attack',...
            'Style', 'rotaryknob',...
            'Label', 'ms',...
            'Mapping', {'int', 1, 50},...
            'Layout', [1,3],...
            'DisplayNameLocation', 'below',...
            'Filmstrip', 'Prophetic_Silver_80x80.png',...
            'FilmstripFrameSize', [80 80]),...
            audioPluginParameter('RELEASE',...
            'DisplayName', 'Release',...
            'Style', 'rotaryknob',...
            'Label', 'ms',...
            'Mapping', {'int', 10, 1000},...
            'Layout', [1,4],...
            'DisplayNameLocation', 'below',...
            'Filmstrip', 'Prophetic_Silver_80x80.png',...
            'FilmstripFrameSize', [80 80]),...
            audioPluginParameter('HI_CENTER_FREQ',...
            'DisplayName', 'High Pass',...
            'Style', 'rotaryknob',...
            'Mapping',{'int',6000,10000},...
            'Layout', [3,1],...
            'DisplayNameLocation', 'below',...
            'Filmstrip', 'Prophetic_Silver_80x80.png',...
            'FilmstripFrameSize', [80 80]),...
            audioPluginParameter('LOW_CENTER_FREQ',...
            'DisplayName', 'Low Pass', ...
            'Style', 'rotaryknob',...
            'DisplayNameLocation', 'below',...
            'Mapping',{'int',50,1000},...
            'Layout', [3,2],...
            'Filmstrip', 'Prophetic_Silver_80x80.png',...
            'FilmstripFrameSize', [80 80]),...
            audioPluginParameter('BAND_CENTER_FREQ',...
            'DisplayName', 'Band Pass', ...
            'Style', 'rotaryknob',...
            'Mapping',{'int',1000,6000},...
            'Layout', [3,3],...
            'DisplayNameLocation', 'below',...
            'Filmstrip', 'Prophetic_Silver_80x80.png',...
            'FilmstripFrameSize', [80 80]),...
            audioPluginParameter('Q_factor',...
            'DisplayName', 'Q', ...
            'Style', 'rotaryknob',...
            'DisplayNameLocation', 'below',...
            'Mapping',{'lin',0,1},...
            'Layout', [3,4],...
            'Filmstrip', 'Prophetic_Silver_80x80.png',...
            'FilmstripFrameSize', [80 80]),...
            audioPluginParameter('HI_GAIN',...
            'DisplayName', 'HP Gain', ...
            'Style', 'rotaryknob',...
            'DisplayNameLocation', 'below',...
            'Mapping',{'lin',-12,12},...
            'Layout', [5,1],...
            'Filmstrip', 'Prophetic_Silver_80x80.png',...
            'FilmstripFrameSize', [80 80]),...
            audioPluginParameter('LOW_GAIN',...
            'DisplayName', 'LP Gain', ...
            'Style', 'rotaryknob',...
            'DisplayNameLocation', 'below',...
            'Mapping',{'lin',-12,12},...
            'Layout', [5,2],...
            'Filmstrip', 'Prophetic_Silver_80x80.png',...
            'FilmstripFrameSize', [80 80]),...
            audioPluginParameter('BAND_GAIN',...
            'DisplayName', 'LP Gain', ...
            'Style', 'rotaryknob',...
            'DisplayNameLocation', 'below',...
            'Mapping',{'lin',-12,12},...
            'Layout', [5,3],...
            'Filmstrip', 'Prophetic_Silver_80x80.png',...
            'FilmstripFrameSize', [80 80]),...
            audioPluginParameter('DECAY',...
            'DisplayName', 'Decay', ...
            'Style', 'rotaryknob',...
            'DisplayNameLocation', 'below',...
            'Mapping',{'lin',0,1},...
            'Layout', [5,4],...
            'Filmstrip', 'Prophetic_Silver_80x80.png',...
            'FilmstripFrameSize', [80 80]),...
            audioPluginParameter('MIX',...
            'Style', 'rotaryknob',...
            'Label', '%',...
            'DisplayName', 'Mix',...
            'Mapping', {'int', 0, 100},...
            'Layout', [7,1],...
            'DisplayNameLocation', 'below',...
            'Filmstrip', 'Prophetic_Silver_80x80.png',...
            'FilmstripFrameSize', [80 80]),...
            audioPluginParameter('BYPASS',...
            'Layout', [7,4],...
            'Mapping',{'enum','engage','bypass'},...
            'Filmstrip', '3-D_Stainless_Switch_2_positions_x4_shadow.png',...
            'DisplayName', ' ',...
            'FilmstripFrameSize', [50 60])...
            );
        %'Mapping',{'enum','engage','bypass'},...
    end

    properties (Access = private)
        compressor;
        reverb;

        filter_HPF = struct('w', [0 0; 0 0], 'a0', 1, 'a1', 0, 'a2', 0, 'b0', 1, 'b1', 0, 'b2', 0);
        filter_LPF = struct('w', [0 0; 0 0], 'a0', 1, 'a1', 0, 'a2', 0, 'b0', 1, 'b1', 0, 'b2', 0);
        filter_BPF = struct('w', [0 0; 0 0], 'a0', 1, 'a1', 0, 'a2', 0, 'b0', 1, 'b1', 0, 'b2', 0);

        HI_SMOOTH;
        HI_GAIN_SMOOTH;
        LOW_SMOOTH;
        LOW_GAIN_SMOOTH;
        BAND_SMOOTH;
        BAND_GAIN_SMOOTH;
        Q_SMOOTH;
        DECAY_SMOOTH;
        MIX_SMOOTH;

        out1
        out2
        out3

    end
    methods
        function plugin = EQ()
            smoothing_val = 0.9;
            plugin.HI_SMOOTH = ParameterSmoother(plugin.HI_CENTER_FREQ, smoothing_val);
            plugin.HI_GAIN_SMOOTH = ParameterSmoother(plugin.HI_GAIN, smoothing_val);
            plugin.LOW_SMOOTH = ParameterSmoother(plugin.LOW_CENTER_FREQ, smoothing_val);
            plugin.LOW_GAIN_SMOOTH = ParameterSmoother(plugin.LOW_GAIN, smoothing_val);
            plugin.BAND_SMOOTH = ParameterSmoother(plugin.BAND_CENTER_FREQ, smoothing_val);
            plugin.BAND_GAIN_SMOOTH = ParameterSmoother(plugin.BAND_GAIN, smoothing_val);
            plugin.Q_SMOOTH = ParameterSmoother(plugin.Q_factor, smoothing_val);
            plugin.DECAY_SMOOTH = ParameterSmoother(plugin.DECAY, smoothing_val);
            plugin.MIX_SMOOTH = ParameterSmoother(plugin.MIX, smoothing_val);
            plugin.compressor = compressor('Threshold', plugin.THRESHOLD,...
                'Ratio', plugin.RATIO, ...
                'AttackTime',plugin.ATTACK/1000,...
                'ReleaseTime',plugin.RELEASE/1000,...
                'MakeUpGainMode','Auto');
            plugin.reverb = reverberator('PreDelay', 0,...
                'WetDryMix', plugin.MIX/100,...
                'DecayFactor', plugin.DECAY);

            plugin.out1 = dsp.AsyncBuffer;
            plugin.out2 = dsp.AsyncBuffer;
            plugin.out3 = dsp.AsyncBuffer;
        end

        function out = process(plugin, in)
            out = coder.nullcopy(zeros(size(in)));
            numChannels = size(in,2);

            reverberator;

            update_HPF(plugin);
            update_LPF(plugin);
            update_BPF(plugin);

            for ch = 1:numChannels

                if strcmp(plugin.BYPASS, 'bypass')
                    out = in;
                return;
                end

                x = in(:,ch);

                
                [x, plugin.filter_HPF.w(:,ch)] = processBiquad(x, plugin.filter_HPF, ch);
                [x, plugin.filter_LPF.w(:,ch)] = processBiquad(x, plugin.filter_LPF, ch);
                [x, plugin.filter_BPF.w(:,ch)] = processBiquad(x, plugin.filter_BPF, ch);


                filtered_signal = x;

                    write(plugin.out1,filtered_signal);
                    out(:, ch) = plugin.compressor(read(plugin.out1));
                    


            end
            if strcmp(plugin.BYPASS, 'bypass')
                out = in;
                return;
            else
                out(:,:) = plugin.reverb(out);
            end
            
        end

        function reset(plugin)
            plugin.fs = getSampleRate(plugin);
            plugin.fn = plugin.fs / 2;

            plugin.filter_HPF.w = [0 0; 0 0];
            plugin.filter_LPF.w = [0 0; 0 0];
            plugin.filter_BPF.w = [0 0; 0 0];

        end

        function set.HI_CENTER_FREQ(plugin, val)
            plugin.HI_CENTER_FREQ = val;
            plugin.HI_SMOOTH.setTargetValue(val);
        end

        function set.HI_GAIN(plugin, val)
            plugin.HI_GAIN = val;
        end

        function update_HPF(plugin)

            
            thetaC = (2.0*pi*plugin.HI_SMOOTH.step()) / plugin.fs;
            d  = 1 / plugin.Q_SMOOTH.step();
            %mu = pow(10,plugin.HI_GAIN_SMOOTH.step()/20.0);
            betaTop = (1-((d/2)*sin(thetaC)));
            betaBottom =(1+((d/2)*sin(thetaC)));
            beta = 0.5 * (betaTop/betaBottom);
            gamma = (0.5 + beta)*cos(thetaC);
            plugin.filter_HPF.a0 = (0.5+beta+gamma)/2.0;
            plugin.filter_HPF.a0 = -1.0*(0.5+beta+gamma);
            plugin.filter_HPF.a2 = (0.5+beta+gamma)/2.0;
            %plugin.filter_HPF.b0 = 1 + alpha;
            plugin.filter_HPF.b1 = -2*gamma;
            plugin.filter_HPF.b2 = 2*beta;
            %}

        end


        function set.LOW_CENTER_FREQ(plugin, val)
            plugin.LOW_CENTER_FREQ = val;
            plugin.LOW_SMOOTH.setTargetValue(val);
        end

        function set.LOW_GAIN(plugin, val)
            plugin.LOW_GAIN = val;
        end


        function update_LPF(plugin)

            thetaC = (2.0*pi*plugin.LOW_SMOOTH.step())/plugin.fs;
            d  = 1 / plugin.Q_SMOOTH.step();
            betaTop = (1-((d/2.0)*sin(thetaC)));
            %mu = pow(10,gainKnobvalue/20.0);
            betaBottom =(1+((d/2.0)*sin(thetaC)));
            beta = 0.5 * (betaTop/betaBottom);
            gamma = (0.5 + beta)*cos(thetaC);
            plugin.filter_LPF.a0 = (0.5+beta-gamma)/2.0;
            plugin.filter_LPF.a1 = (0.5+beta-gamma);
            plugin.filter_LPF.a2 = (0.5+beta-gamma)/2.0;
            %plugin.filter_LPF.b0 = 1 + alpha;
            plugin.filter_LPF.b1 = -2*gamma;
            plugin.filter_LPF.b2 = 2*beta;

        end


        function set.BAND_CENTER_FREQ(plugin, val)
            plugin.BAND_CENTER_FREQ = val;
            plugin.BAND_SMOOTH.setTargetValue(val);
        end

        function set.BAND_GAIN(plugin, val)
            plugin.BAND_GAIN = val;
        end


        function update_BPF(plugin)

            thetaC = (2.0*pi*plugin.BAND_SMOOTH.step())/plugin.fs;
            betaTop = (1.0-tan(thetaC/(2.0*plugin.Q_SMOOTH.step())));
            betaBottom =(1.0+tan(thetaC/(2.0*plugin.Q_SMOOTH.step())));
            beta = 0.5 * (betaTop/betaBottom);
            gamma = (0.5+beta)*cos(thetaC);
            plugin.filter_BPF.a0 = 0.5-beta;
            plugin.filter_BPF.a1 = 0.0;
            plugin.filter_BPF.a2 = -1.0*(0.5-beta);
            plugin.filter_BPF.b1 = -2*gamma;
            plugin.filter_BPF.b2 = 2*beta;

        end

        
        function [y, filt] = processBiquad_Nick(plugin,x, filt, ch)
            wn_1 = filt.w(1, ch);
            wn_2 = filt.w(2, ch);

            numChannels = size(x,2);
            numSamples = size(x,1);

            y = zeros(numSamples, numChannels);

            for n = 1:numSamples
                w = x(n) - (filt.a1 * wn_1) - (filt.a2 * wn_2);
                y(n) = (filt.b0 * w) + (filt.b1 * wn_1) + (filt.b2 * wn_2);
                wn_2 = wn_1;
                wn_1 = w;
            end

            filt.w(1,ch) = wn_1;
            filt.w(2,ch) = wn_2;
        end

        function set.DECAY(plugin, val)
            plugin.DECAY = val;
            plugin.DECAY_SMOOTH.setTargetValue(val);%#ok
            updateReverb(plugin);
        end

        function set.MIX(plugin, val)
            plugin.MIX = val;
            plugin.MIX_SMOOTH.setTargetValue(val);%#ok
            updateReverb(plugin);
        end

        function updateReverb(plugin)
            plugin.reverb.WetDryMix = plugin.MIX/100;
            plugin.reverb.DecayFactor = plugin.DECAY;
        end


        function set.THRESHOLD(plugin, val)
            plugin.THRESHOLD = val;
            updateCompressor(plugin);
        end

        function set.RATIO(plugin, val)
            plugin.RATIO = val;
            updateCompressor(plugin);
        end

        function set.ATTACK(plugin, val)
            plugin.ATTACK = val;
            updateCompressor(plugin);
        end

        function set.RELEASE(plugin, val)
            plugin.RELEASE = val;
            updateCompressor(plugin);
        end

        function updateCompressor(plugin)
            plugin.compressor.Threshold = plugin.THRESHOLD;
            plugin.compressor.Ratio = plugin.RATIO;
            plugin.compressor.AttackTime = plugin.ATTACK/1000;
            plugin.compressor.ReleaseTime = plugin.RELEASE/1000;
        end

    end

end